apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  postgres-password: YWRtaW4xMjM=
  SECRET_KEY: bS0rbChhMDRqXiRzanAhN2QtMzRjIyRybW9yXj1rMyNkXzYjMDB2d2VtYiUjaiExYjI=
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczphZG1pbjEyM0Bwb3N0Z3Jlczo1NDMyL211c2ljX3BsYXRmb3Jt
  LASTFM_KEY: NDliNjIxMzM5NmE0YjVhMjE2MzdiY2Y2MjdhNGJmM2Q=
  DJANGO_SUPERUSER_PASSWORD: cGFzc3dvcmQxMjM=